spring:
  application:
    name: posBilling

  datasource:
    url: jdbc:mysql://localhost:3306/posB
    username: root
    password: password

  jpa:
    # show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: suvadip.web*****@gmail.com
    password: olmf flzh iecb axaj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8888

bucket-name: pos-bill-application
aws:
  s3:
    access:
      key: AKIAZ7SAK3YFYV3YOHJD73
    secret:
      key: kEjYotDygwQtewe8PIT52eSgp88349384034hjdf

API_URL: https://graph.facebook.com/v22.0/557890804076465/messages

APP_ID: 1715159599062970
APP_SECRET: 33b105e854945d3cae4b6d7e390715hdjhd
